In [4]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [39]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [21]:
arquivo = 'z0019_2.csv'
data_ingestao = datetime.now()
df = pd.read_csv(f'../landing/{arquivo}', sep=';')
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

   NATBR    MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10004    SERRA  BT50    100    200  z0019_2.csv 2026-03-03 20:15:09.011823
1  10005  MACHADO  BT50    100    100  z0019_2.csv 2026-03-03 20:15:09.011823
2  10003    PREGO  BT50    100     60  z0019_2.csv 2026-03-03 20:15:09.011823

In [18]:
con.execute(
    """
        CREATE TABLE IF NOT EXISTS bronze_produto(
            NATBR VARCHAR,
            MAKTX VARCHAR,
            WERKS VARCHAR,
            MAINS VARCHAR,
            LABST VARCHAR,
            nome_arquivo VARCHAR,
            data_ingestao TIMESTAMP,
            
        )
"""
)

In [23]:
con.execute("INSERT INTO bronze_produto SELECT * FROM df")

In [34]:
# con.execute("delete from bronze_produto where data_ingestao in ('2026-03-03 20:15:09.011823')")

In [44]:
resultado = con.execute("select * from bronze_z0019").fetchdf()
display(resultado)

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-03-03 20:05:41.436583
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-03-03 20:05:41.436583
2  10003     PREGO  BT50   100    50  z0019_1.csv 2026-03-03 20:05:41.436583
3  10004     SERRA  BT50   100   200  z0019_2.csv 2026-03-03 20:13:27.697959
4  10005   MACHADO  BT50   100   100  z0019_2.csv 2026-03-03 20:13:27.697959
5  10003     PREGO  BT50   100    60  z0019_2.csv 2026-03-03 20:13:27.697959

In [42]:
con.execute("ALTER TABLE bronze_produto RENAME TO bronze_z0019")

In [47]:
con.close()